### ISSUE TITLE
程序奔溃了 runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nanoiii** [hanbang-wang/Yun-Brute#3]
运行 `./brute https://pan.baidu.com/s/1nvCqnvb`
```
2016/11/09 16:23:30 Unknown error! Service returned 1 with message: ""
2016/11/09 16:24:40 Unknown error! Service returned 1 with message: ""
2016/11/09 16:24:42 Unknown error! Service returned 1 with message: ""
2016/11/09 16:26:41 Unknown error! Service returned 1 with message: ""
2016/11/09 16:33:01 Unknown error! Service returned 1 with message: ""
2016/11/09 16:33:04 Get http://proxy.tekbreak.com/1000/json: dial tcp: lookup proxy.tekbreak.com on 211.138.113.115:53: read udp 192.168.0.10:45621->211.138.113.115:53: i/o timeout
[>-------------------------------------------]   0.07% 1/s 11d7h14m24spanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13a20]

goroutine 25 [running]:
panic(0x307b10, 0x10722008)
        /usr/local/go/src/runtime/panic.go:500 +0x33c
main.saveProxies.func2()
        /home/nano/Yun-Brute/brute.go:165 +0xa0
created by main.init.1
        /home/nano/Yun-Brute/brute.go:396 +0x318
```

**Comment by superfashi** [comment]
啊啊啊这个bug很严重啊，属于我粗心了，感谢。
